### PR TITLE
Add completions for ADB/Scrcpy/Fastboot

### PR DESCRIPTION
**Pull request by DRSDavidSoft**
This is based off of https://github.com/vladimir-kotikov/clink-completions/pull/149, so it should be merged first.

### Description
Added the completions for the android debugging tool and scrcpy, developed by **[Goldie Lin](https://github.com/goldie-lin)**

### CODE REVIEW

**Comment by chrisant996** [comment]
I'll look at this after merging my big git.lua rewrite. There might be merge conflicts.

**Comment by chrisant996** [comment]
Some feedback before merging this PR:
1. Why do the lua script files define both an argmatcher and a separate match generator? Can they instead use the [Functions As Argument Options](https://chrisant996.github.io/clink/clink.html#argmatcher_functions) syntax in Clink, and define only an argmatcher?
2. What is the purpose for using `null_parser` in so many places? It seems like that may interfere with completions in the rest of the command line.
3. Can you update the Clink web links to point to the current repo, i.e. https://github.com/chrisant996/clink?

**Comment by DRSDavidSoft** [comment]
@chrisant996 I will respond in the issue here:
https://github.com/chrisant996/clink-completions/pull/1

**Comment by chrisant996** [comment]
> @chrisant996 I will respond in the issue here: [chrisant996#1](https://github.com/chrisant996/clink-completions/pull/1)

This repo, i.e. Vladimir's repo, is still the main one, and will continue to make releases. He made me a co-owner of the repo so that I can maintain his repo.

Let's let Goldie respond in the forked PR, and then we can proceed in this original PR.

I can potentially move the generator implementation into a match function so that it's fully integrated into the argmatcher and can work properly even in a line that contains multiple commands (e.g. `pushd foo & fastboot`).

But I don't have adb or srcpy or fastboot, and I don't understand what syntax the generator is meant to respond to.  And I don't understand all the null_parser usages.  It looks like there are problems in the implementation, but I'm not sure whether I can safely fix them myself without more context about how it's intended to behave.

**Comment by chrisant996** [comment]
I added these in the `dev` branch and made some syntax changes.  So they are in now, but not yet in `master`.

**Pull request closed without merging**
