### PR TITLE
Update `eza` and fix long options missing help text.

### PR DESCRIPTION
**Pull request by plutonium-239**
I've added some options that are new in `eza`.

The help text was missing in the long options; I've added it. I don't know if it was on purpose, but it's more useful with it since that is the whole point of being able to search through the options and their descriptions.

### CODE REVIEW

**Comment by chrisant996** [comment]
The description text is intentionally missing from long options, because:
1. Long option names are typically reasonably self-descriptive.
2. It enables multiple columns of display, instead of forcing everything into a single column.

I first observed this approach in various completion scripts for other shells, and it made a lot of sense to me.

image

**Comment by plutonium-239** [comment]
Can you get columns with the `fzf` integration?

**Comment by chrisant996** [comment]
> Can you get columns with the `fzf` integration?

As far as I know, fzf doesn't have a columnar view.

(But Clink and other scripts shouldn't assume that fzf will be used.)

**Comment by chrisant996** [comment]
I don't want descriptions on the long options.
I took the other changes and applied them (with some modifications).

**Pull request closed without merging**
