### PR TITLE
Update prompt with git branch.

### LINKED ISSUE #49: Git prompt example?
Is anyone using a git prompt, something that shows current branch etc? If so, can you share it so I can copy/modify :)

### PR DESCRIPTION
**Pull request by idvorkin**
Update prompt with git branch, resolves #49. 

To use set {git} in your PROMPT statement

### CODE REVIEW

**Comment by idvorkin** [comment]
I just found out conemu supports showing git command line via: 

   gitshowbranch /i

I suspect most people would prefer that.

**Comment by vladimir-kotikov** [comment]
I'm curious - is there reasons not to use ConEmu? It does what you want out-of-the box.

**Comment by idvorkin** [comment]
ConEmu's method is too slow.

**Comment by vladimir-kotikov** [comment]
> ConEmu's method is too slow

Sorry, i meant Cmder :)

**Comment by idvorkin** [comment]
I don't recall why I stopped using cmder last time, I"ll give it another go.

**Comment by vladimir-kotikov** [comment]
I understand that people might want to use this outside Cmder, but I don't want to add already implemented functionality. Moreover, making this working smoothly with Cmder would be a pain.

**Pull request closed without merging**
