### PR TITLE
fix gsub branch when folder contains branch name

### PR DESCRIPTION
**Pull request by daxgames**
Fixes https://github.com/cmderdev/cmder/issues/2116
Fixes https://github.com/cmderdev/cmder/issues/1979
Fixes https://github.com/vladimir-kotikov/clink-completions/issues/104

### CODE REVIEW

**Comment by daxgames** [comment]
@vladimir-kotikov ^^^

**Comment by daxgames** [comment]
Bump

**Comment by vladimir-kotikov** [comment]
@daxgames do you want me to publish a new release?

**Comment by daxgames** [comment]
If you are comfortable doing that yes.  That wiuld allow us to include this fix in cmder.

**Comment by vladimir-kotikov** [comment]
Ok, I'll try to get a new release today

**Comment by vladimir-kotikov** [comment]
@daxgames here you go: https://github.com/vladimir-kotikov/clink-completions/releases/tag/0.3.4

**Comment by daxgames** [comment]
Thanks

**Pull request merged**
