### PR TITLE
Add completions for arguments for git aliases

### LINKED ISSUE #147: Support argument completion for aliased commands
`git.lua` provides tab-completions for git commands and its arguments. It also provides completion for aliases. But it does not provide proper argument completion for those aliased commands. For example, with `alias.co checkout`, when we press tab after `git co |` (| being the cursor), it should provide completion for the git branches, just as it does for `git checkout` command.

### PR DESCRIPTION
**Pull request by 3N4N**
Closes #147 

clink-completions provides completions for git aliases, but not for the arguments those aliases would accept. This PR adds that support.

#### What it does

With `co` aliased to `checkout`, you can now tab-complete the branch names after writing `git co `.

#### What it doesn't

It doesn't support complex aliases, or aliases with any arguments, really. For example, with `co` aliased to `checkout -b`, you cannot tab-complete branches after `git co `.

### CODE REVIEW

**Comment by 3N4N** [comment]
@albfan @vladimir-kotikov this is a continuation of #24

**Comment by chrisant996** [comment]
Please don't merge this.

I have a large set of enhancements for the git parser that I'm about to make a PR for, and it already addresses aliases.

**Comment by chrisant996** [comment]
The change in this PR runs git every time Clink is started.  That is a fairly significant extra slowdown introduced into all Clink startups (even running `clink info` or `clink set`, which have to load the Lua engine and all scripts, since scripts may define settings and so on).

It also changes the alias handling such that any changes one makes to aliases during the Clink session will not take effect until the next Clink session.  Previously, changes to aliases take effect immediately.

I have a different approach that should solve that performance problem.

It uses `argmatcher:setdelayinit()` to defer running git to collect aliases until the first time git is actually used in the Clink session, and also when switching to a different repo.  It still adds an `alias` function into the parser, so that generating completions picks up any alias changes immediately, but argument/flag parsing only picks up alias changes when switching to a different repo.

**Comment by 3N4N** [comment]
@chrisant996 My commit is only a hack. I found this repo only today, saw that it didn't work with aliased commands, looked into it, and wrote a hack. I don't even know lua, let along clink completions. So there's that. But --

> It still adds an alias function into the parser, so that generating completions picks up any alias changes immediately

I didn't remove the `alias` function. I added a separate `aliases` function that returns all the aliases with command and alias as key and value respectively. The parser still uses the previous `alias` function and picks up on alias changes (because it runs `alias` on every completion, I assume.) And --

> argument/flag parsing only picks up alias changes when switching to a different repo.

My commit could be changed to handle this scenario. I would just need to wrap all I have done in a function and return the complete table with new aliases (if added). The `git_parser` could call that function and add the returned table to its parser.

---

This is not me justifying my code to you. There is nothing to justify. I wrote a hack. In an hour. In a language I know nothing about. I am just pointing out one thing you thought wrong (the `alias` function). That's it.

**Comment by chrisant996** [comment]
> @chrisant996 My commit is only a hack. I found this repo only today, saw that it didn't work with aliased commands, looked into it, and wrote a hack. I don't even know lua, let along clink completions. So there's that. But --

Well done!  I like the idea, which is why I expanded on the idea.  Thank you for contributing to the Clink community!

> > It still adds an alias function into the parser, so that generating completions picks up any alias changes immediately
> 
> I didn't remove the `alias` function. I added a separate `aliases` function that returns all the aliases with command and alias as key and value respectively. The parser still uses the previous `alias` function and picks up on alias changes (because it runs `alias` on every completion, I assume.) And --

Ah, got it.  I missed that in the diffs, sorry.  The diffs were large, and I hadn't done an exhaustive analysis of them.

> > argument/flag parsing only picks up alias changes when switching to a different repo.
> 
> My commit could be changed to handle this scenario. I would just need to wrap all I have done in a function and return the complete table with new aliases (if added). The `git_parser` could call that function and add the returned table to its parser.

Yes.  It's more complicated, though, because of limitations in Clink due to performance reasons.

(Quick sidebar:  when I share explanations, it's coming from a motivation of wanting to share knowledge for future readers.  I view capturing information in issues and discussions as useful to others.)

Unfortunately, argmatchers only invoke embedded functions when generating completions -- they aren't invoked when parsing or coloring the input line, as that would cause a lot of lag and constant invocations of other processes on every keystroke.  Clink's Lua API could be redesigned to mitigate that somewhat, but at the cost of increased complexity for script authors, and I don't see a way to fully mitigate it.

In order for the aliases to participate in parsing and coloring, there are two options:  (1) they have to be set during creation of the argmatcher or (2) the argmatcher can be written to use "delay init" and then it can even reset itself and re-initialize when needed.

The latter is unfortunately a bit more complicated to code up.  I'm still looking for ways to make it simpler, though.  In attempt to help the Clink community, I've implemented the "delay init" approach for the alias parsers.  And then I'm just trying to describe what I've done, so that there is a record of it for future reference.

That's all I'm trying to do.  I apologize for any offense I have caused along the way!

**Comment by 3N4N** [comment]
@chrisant996 no offence taken. specially in this thread. The discussion in your clink repo was just weird, not offensive. And thanks for working on clink. Otherwise I'd have had to stay with powershell and suffer its terrible startup time. Hope your future developments comes swift and bugless. Cheers.

**Pull request closed without merging**
